# Generated by Django 6.1.1 on 2026-10-02 11:48

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_membership_id_alter_organization_id_and_more'),
        ('vehicles', '0002_vehicle_assigned_drivers_vehicle_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['organization', '-created_at'], name='vehicle_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['owner', '-created_at'], name='vehicle_owner_created_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['organization', 'is_active'], name='vehicle_org_active_idx'),
        ),
    ]
