# Generated by Django 6.1.1 on 2026-10-07 19:48

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_plan_planfeature_subscription'),
        ('vehicles', '0003_alter_vehicle_id_vehicle_vehicle_org_created_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(max_length=120)),
                ('service_date', models.DateField()),
                ('odometer_km', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('parts_replaced', models.JSONField(blank=True, default=list)),
                ('technician', models.CharField(blank=True, max_length=150)),
                ('service_center', models.CharField(blank=True, max_length=180)),
                ('notes', models.TextField(blank=True)),
                ('client_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='accounts.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-service_date', '-created_at'],
                'indexes': [models.Index(fields=['vehicle', '-service_date'], name='service_vehicle_date_idx'), models.Index(fields=['owner', '-service_date'], name='service_owner_date_idx'), models.Index(fields=['organization', '-service_date'], name='service_org_date_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('client_id__isnull', False)), fields=('owner', 'client_id'), name='service_owner_client_id_unique')],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(max_length=120)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_odometer_km', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('dismissed', 'Dismissed')], default='open', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_reminders', to='accounts.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_reminders', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_reminders', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['status', 'due_date', 'due_odometer_km'],
                'indexes': [models.Index(fields=['vehicle', 'status', 'due_date'], name='reminder_vehicle_status_idx'), models.Index(fields=['owner', 'status'], name='reminder_owner_status_idx'), models.Index(fields=['organization', 'status'], name='reminder_org_status_idx')],
            },
        ),
    ]
