# Generated by Django 6.1.1 on 2026-10-07 19:48

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_plan_planfeature_subscription'),
        ('vehicles', '0003_alter_vehicle_id_vehicle_vehicle_org_created_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_location', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('start_odometer_km', models.PositiveIntegerField(blank=True, null=True)),
                ('end_odometer_km', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel_consumed_liters', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('fuel_price_per_liter', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fuel_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('client_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='accounts.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['vehicle', '-started_at'], name='trip_vehicle_started_idx'), models.Index(fields=['owner', '-started_at'], name='trip_owner_started_idx'), models.Index(fields=['organization', '-started_at'], name='trip_org_started_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ended_at__gt', models.F('started_at'))), name='trip_end_after_start'), models.CheckConstraint(condition=models.Q(('start_odometer_km__isnull', True), ('end_odometer_km__isnull', True), ('end_odometer_km__gte', models.F('start_odometer_km')), _connector='OR'), name='trip_odometer_non_decreasing'), models.UniqueConstraint(condition=models.Q(('client_id__isnull', False)), fields=('owner', 'client_id'), name='trip_owner_client_id_unique')],
            },
        ),
    ]
