# Generated by Django 6.1.1 on 2026-10-07 19:48

import django.db.models.deletion
import preferences.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('alert_settings', models.JSONField(default=preferences.models.default_alert_settings)),
                ('thresholds', models.JSONField(default=preferences.models.default_thresholds)),
                ('units', models.CharField(choices=[('metric', 'Metric'), ('imperial', 'Imperial')], default='metric', max_length=10)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('language', models.CharField(default='en', max_length=10)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['updated_at'], name='pref_updated_idx')],
            },
        ),
    ]
