# Generated by Django 6.1.1 on 2026-10-07 19:48

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_plan_planfeature_subscription'),
        ('vehicles', '0003_alter_vehicle_id_vehicle_vehicle_org_created_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('odometer_km', models.PositiveIntegerField()),
                ('quantity_liters', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('lpg', 'LPG')], default='petrol', max_length=10)),
                ('station', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('is_full_tank', models.BooleanField(default=False)),
                ('client_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_records', to='accounts.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_records', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_records', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['vehicle', '-date'], name='fuel_vehicle_date_idx'), models.Index(fields=['owner', '-date'], name='fuel_owner_date_idx'), models.Index(fields=['organization', '-date'], name='fuel_org_date_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('client_id__isnull', False)), fields=('owner', 'client_id'), name='fuel_owner_client_id_unique')],
            },
        ),
    ]
